<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>AuthSuite2</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>b5de6744-5e36-4b9a-888c-cce20199e667</testSuiteGuid>
   <testCaseLink>
      <guid>4cfcedfd-fc26-49a8-89ba-6ec95574a934</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Auth/LoginFailed2</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>0cb347c7-7a9b-4b63-a8f8-436d0b20bab3</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/LoginFailed2</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>0cb347c7-7a9b-4b63-a8f8-436d0b20bab3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>56895a41-c89d-47c3-95bc-8caecb2a0edb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>0cb347c7-7a9b-4b63-a8f8-436d0b20bab3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>1067fe04-557e-43b6-8e2d-2f5e90acb9b6</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
