<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>AuthSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>c31ee5be-c664-48da-ba3f-def6e0119930</testSuiteGuid>
   <testCaseLink>
      <guid>e4076205-06b9-4096-a703-e007d17aaac8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Auth/LoginFailed</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>4c1510b3-7dd1-44a7-8c38-4167de3083ed</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/LoginFailedData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>4c1510b3-7dd1-44a7-8c38-4167de3083ed</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>c932553e-8cc2-45e0-80b5-6d38c1c23d58</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>4c1510b3-7dd1-44a7-8c38-4167de3083ed</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>2dea025a-69d1-4969-bf39-d7007bc57ea4</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
