<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Beranda</name>
   <tag></tag>
   <elementGuidId>9d6ef31c-4552-4e50-8bea-ccac00f8e709</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[(text() = 'Beranda' or . = 'Beranda')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.menu-item-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b977f59c-2cef-42cb-a865-6292678bb1e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-item-text</value>
      <webElementGuid>75383263-557d-4a8f-bb89-34875995edf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Beranda</value>
      <webElementGuid>42a0d21e-c935-4f50-a55a-5cc8a8251824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;fontawesome-i2svg-active fontawesome-i2svg-complete&quot;]/body[1]/div[@class=&quot;app&quot;]/div[@class=&quot;tile is-ancestor&quot;]/div[@class=&quot;tile is-child is-sidebar&quot;]/div[@class=&quot;sidebar is-narrow-mobile is-fullheight is-hidden-mobile&quot;]/ul[@class=&quot;menu-list&quot;]/li[42]/a[@class=&quot;menu-item router-link-exact-active is-active&quot;]/div[@class=&quot;menu-item-text&quot;]</value>
      <webElementGuid>ada47df0-30b4-4b16-8048-49df78a29262</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Smart Search'])[1]/preceding::div[2]</value>
      <webElementGuid>18d228b3-33c5-4442-89ee-fc2440c508a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laporan'])[1]/preceding::div[4]</value>
      <webElementGuid>29df5cec-47e5-4ed5-8c87-ecf4f551ff79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Beranda']/parent::*</value>
      <webElementGuid>4fd35a1d-8fbc-4b39-adda-a17172fa4968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div[2]</value>
      <webElementGuid>eabf374a-f982-4a4c-af21-e2b6692957dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Beranda' or . = 'Beranda')]</value>
      <webElementGuid>a56bdde0-38f4-49e2-b95c-b3d94327a6c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
