<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Konfigurasi Pabrik</name>
   <tag></tag>
   <elementGuidId>1f7fb37d-bb57-4615-bd2c-c485e381db1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='KonfigurasiPabrik']/div/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#KonfigurasiPabrik > div.collapse-trigger > div.menu-item > div.menu-item-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b921dc9a-3cc6-4d03-882b-67ffc4ef1745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-item-text</value>
      <webElementGuid>af62c27f-9aee-48fa-82d3-41c76a99676c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Konfigurasi Pabrik</value>
      <webElementGuid>a5c0a01a-46ca-4414-a43a-c7a95d5e7088</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;KonfigurasiPabrik&quot;)/div[@class=&quot;collapse-trigger&quot;]/div[@class=&quot;menu-item&quot;]/div[@class=&quot;menu-item-text&quot;]</value>
      <webElementGuid>c9a6dbef-8d25-4316-910d-6577d604c146</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='KonfigurasiPabrik']/div/div/div[2]</value>
      <webElementGuid>af2bb978-e136-4bdd-bcf0-3fd365d07df0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Penomoran Otomatis'])[1]/following::div[5]</value>
      <webElementGuid>25b73232-4299-4797-8dff-94db3fd95bb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cara Pembayaran'])[1]/following::div[8]</value>
      <webElementGuid>71236844-e6b0-462c-b626-121093541b66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Satuan Pengukuran'])[1]/preceding::div[4]</value>
      <webElementGuid>e85564bc-d848-45a7-b558-4c69050fcd13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Harga Barang'])[1]/preceding::div[7]</value>
      <webElementGuid>6028085c-45b5-4a43-9934-86f25a5850c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Konfigurasi Pabrik']/parent::*</value>
      <webElementGuid>711ba83a-4ada-4b3f-bb53-9056e71771b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[50]/div/div/div/div[2]</value>
      <webElementGuid>aed845c3-0061-4cce-899e-5cab436e07d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Konfigurasi Pabrik' or . = 'Konfigurasi Pabrik')]</value>
      <webElementGuid>0743d503-68a8-4ab7-bc98-04b96231385b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
