<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Jenis Diskon_selectedDiscountType</name>
   <tag></tag>
   <elementGuidId>2200f776-755e-4100-8534-672e1f6b5b11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='selectedDiscountType']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;selectedDiscountType&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2f159f86-3f0c-4da2-93a7-4f39919b3549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a0b163fe-6c49-4b36-8c85-9c57c19462d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>28fbf2ee-b84e-42d9-81cc-50abaeaa06ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>562446c1-9794-4c48-a1ec-cfb67da3d5a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>selectedDiscountType</value>
      <webElementGuid>dde4fa73-5375-4763-84d0-93601f275050</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pilih jenis diskon</value>
      <webElementGuid>80bf6691-be65-4b4f-9923-235d7dab0928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>search-fields</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>7829b496-46c3-4383-b563-ddd5c5c82c0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6cc21531-d185-4413-a79f-9c57fd90d5a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;581-content&quot;)/div[@class=&quot;app-content&quot;]/div[@class=&quot;items-price-form&quot;]/div[@class=&quot;content section-card&quot;]/div[@class=&quot;columns has-custom-margin-btm&quot;]/div[@class=&quot;column is-shared-bselect&quot;]/div[@class=&quot;field&quot;]/div[@class=&quot;autocomplete control&quot;]/div[@class=&quot;control has-icons-right is-clearfix&quot;]/input[@class=&quot;input&quot;]</value>
      <webElementGuid>521405b4-afb2-4406-af62-6d33e7a4f088</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='selectedDiscountType']</value>
      <webElementGuid>a98bf38b-b8d6-4905-9ebd-3e37cf4206be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='581-content']/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>bdb93734-9c75-4ad7-80be-23d1c9ea4b1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>a2c4805c-07d1-4eaf-9cd0-3509a61b6cd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'selectedDiscountType' and @placeholder = 'Pilih jenis diskon']</value>
      <webElementGuid>75b69340-d037-4829-a6a3-7129614ae854</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
