<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>LoginSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>b2b69972-0ebd-4930-89c5-0f29a3e2850c</testSuiteGuid>
   <testCaseLink>
      <guid>5bfc4dd7-7fb7-4dcb-b123-9191667e2635</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Auth/Login_Negative</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>80832552-f0cd-402e-9eac-870f557a52c0</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Auth/Login_Negative</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>80832552-f0cd-402e-9eac-870f557a52c0</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>d8061a9c-1101-473d-b97b-32d26e9cd057</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>80832552-f0cd-402e-9eac-870f557a52c0</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>2634da95-0b1f-4d02-9a6f-0fe4d7577daa</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fe066214-80ab-4455-b7b7-77edfa52e652</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Auth/LoginSuccess</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
