<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Inventaris</name>
   <tag></tag>
   <elementGuidId>46fc0021-8013-48cc-a216-af4584d6b87f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Inventaris > div.collapse-trigger > div.menu-item > div.menu-item-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Inventaris']/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>abc441cc-bfd0-4de4-b40b-652f13dda371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-item-text</value>
      <webElementGuid>0e9c9810-9482-46e3-9139-c4cd53a918ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Inventaris</value>
      <webElementGuid>8215aba6-fe6c-45cb-b0da-1d518716f116</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Inventaris&quot;)/div[@class=&quot;collapse-trigger&quot;]/div[@class=&quot;menu-item&quot;]/div[@class=&quot;menu-item-text&quot;]</value>
      <webElementGuid>85aaf1a6-c98a-4616-90e8-5c8d6645a263</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Inventaris']/div/div/div[2]</value>
      <webElementGuid>e2674665-29f0-443a-8940-81f91716eb8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pemakaian Barang'])[1]/following::div[5]</value>
      <webElementGuid>0ccafea7-9da2-44ec-bc18-e20481dc67c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Penjadwalan'])[1]/following::div[8]</value>
      <webElementGuid>0c28243f-d2b8-467a-ad5b-b658b6b69df6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Barang'])[1]/preceding::div[4]</value>
      <webElementGuid>55bff332-3388-44c0-bfc9-863ae70ba698</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Penyesuaian Stok'])[1]/preceding::div[7]</value>
      <webElementGuid>d37cbc76-b024-4ce0-98d7-95a71f514382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Inventaris']/parent::*</value>
      <webElementGuid>bee5b92c-09f0-48aa-99b0-bbcaae952a05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[48]/div/div/div/div[2]</value>
      <webElementGuid>c5466680-e56c-4ecb-8f87-a7afda2c5ca3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Inventaris' or . = 'Inventaris')]</value>
      <webElementGuid>58e2cff5-7f3f-478b-8393-2835f493b1c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
