<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cari_input</name>
   <tag></tag>
   <elementGuidId>106b1263-43fe-46cb-b71c-ba5fc15a230d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8c791d4f-1b14-4c24-a2b1-67703ab023ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>78143013-5caa-44a1-a274-3d7f50f1fa63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cari dengan Nama Item atau Kode Barang</value>
      <webElementGuid>51a0ff5b-30af-4d99-9b3a-7d200405522e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>88bd63ef-183f-40d6-a3c4-76db06387d64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;fontawesome-i2svg-active fontawesome-i2svg-complete&quot;]/body[1]/div[@class=&quot;app&quot;]/div[@class=&quot;tile is-ancestor&quot;]/div[@class=&quot;tile is-parent is-vertical main-content&quot;]/div[@class=&quot;router-content tile is-child&quot;]/div[@class=&quot;app-content&quot;]/div[@class=&quot;content product-overview&quot;]/div[@class=&quot;content section-card list-filter&quot;]/div[@class=&quot;collapse&quot;]/div[@class=&quot;collapse-content&quot;]/div[@class=&quot;section-content with-separator&quot;]/div[1]/div[@class=&quot;field&quot;]/p[@class=&quot;control has-icons-left&quot;]/input[@class=&quot;input&quot;]</value>
      <webElementGuid>69473382-0d04-458f-9633-6e76e4a65306</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='text']</value>
      <webElementGuid>97f703e1-1695-484d-9809-bf801c9f638a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>633bd358-638a-4740-9b5a-fe70861acb49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Cari dengan Nama Item atau Kode Barang']</value>
      <webElementGuid>9cb4ea8a-c0ff-4157-bb04-11e0f7dd7296</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
