<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ukuran (PxLxT)_itemSize</name>
   <tag></tag>
   <elementGuidId>311aa80a-cb26-476b-8686-311bc74fa6cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;itemSize&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='itemSize']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>db43f55b-3ff9-407c-8829-65500ec07c00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>42790597-600c-4868-b781-89cb5adb1478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>07d7c4be-57ac-4b63-ad9e-28191d322257</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>itemSize</value>
      <webElementGuid>ab4facba-c0c3-46ae-b9bd-3150517346e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ce785c9b-fd5f-452a-b4ac-470e45581ac3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;invoice-mobile&quot;)/div[@class=&quot;section-card modal-content-custom&quot;]/div[@class=&quot;section-content with-separator&quot;]/div[@class=&quot;columns is-multiline&quot;]/div[@class=&quot;column is-7&quot;]/div[@class=&quot;columns is-multiline&quot;]/div[@class=&quot;column is-6&quot;]/div[@class=&quot;control is-clearfix&quot;]/input[@class=&quot;input&quot;]</value>
      <webElementGuid>bb74dd5c-5750-4f63-852b-f7bde67fd33c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='itemSize']</value>
      <webElementGuid>6215e9f8-12b9-439f-8c85-d393a1512c1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='invoice-mobile']/div[2]/div[2]/div[2]/div[4]/div/div/div[2]/input</value>
      <webElementGuid>665fe8b0-3c9e-4398-8391-f3b7b0d02a89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/input</value>
      <webElementGuid>dd057c81-e4c2-4f92-b076-73dc8ae3c6b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'itemSize']</value>
      <webElementGuid>33156955-bdda-4353-a6c9-b39739ddd99a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
