<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Satuan</name>
   <tag></tag>
   <elementGuidId>33abd0dd-8160-483c-9e1f-768b779d0d8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;uom&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='uom']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ebfb84af-ad13-477d-b3f5-125db7e9c7a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fdc26eaf-a4b6-49f9-98dc-92d4ace42ac8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>995e1d19-28b3-446f-b513-ff7d99668259</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>1a259050-cf63-4633-bc09-09c9fe5cb193</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>uom</value>
      <webElementGuid>93b90c5f-6859-49f9-b560-a36c64a6ee8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2d1f095b-4a45-4576-9404-f02883fe3d54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;invoice-mobile&quot;)/div[@class=&quot;section-card modal-content-custom&quot;]/div[@class=&quot;section-content with-separator&quot;]/div[3]/div[@class=&quot;columns form-title&quot;]/div[@class=&quot;column is-5&quot;]/div[@class=&quot;field&quot;]/div[@class=&quot;autocomplete control&quot;]/div[@class=&quot;control has-icons-right is-clearfix&quot;]/input[@class=&quot;input&quot;]</value>
      <webElementGuid>eb9b5529-ea10-4d4f-a9da-e831668eaeeb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='uom']</value>
      <webElementGuid>f8d01194-9330-4c2f-b90f-0c516332b023</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='invoice-mobile']/div[2]/div[2]/div[3]/div/div/div/div/div/input</value>
      <webElementGuid>913594f2-540d-4f83-b31b-e13ab40e1987</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/input</value>
      <webElementGuid>be039c29-eb9c-4ba8-8d6a-4760da8bf51f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'uom']</value>
      <webElementGuid>2fc71c76-e6fa-47c1-bf90-fee1bc586eee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
