<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Netto_netto</name>
   <tag></tag>
   <elementGuidId>b8cd4a6e-ca3f-4dcf-ad9a-fb850b57d649</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/div/div[2]/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;netto&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>66d9ee75-1c7a-4e5e-91ab-7b8a3cb1b07b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7e1f1dd6-9e7c-411b-8c90-cc9d51a6c033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input input</value>
      <webElementGuid>cf264dd4-0639-4a6e-81e5-2db3fba5e819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>netto</value>
      <webElementGuid>1d20bb61-9566-401e-9e43-7a25be6c3763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;invoice-mobile&quot;)/div[@class=&quot;section-card modal-content-custom&quot;]/div[@class=&quot;section-content with-separator&quot;]/div[3]/div[@class=&quot;columns form-title&quot;]/div[@class=&quot;column&quot;]/div[@class=&quot;field&quot;]/input[@class=&quot;input input&quot;]</value>
      <webElementGuid>f00a043d-edfd-4f9c-8b8c-bec1b0373c11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='netto']</value>
      <webElementGuid>f0e2872f-abc1-4919-b25b-594eccfa8559</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='invoice-mobile']/div[2]/div[2]/div[3]/div/div[2]/div/input</value>
      <webElementGuid>f6d2a4d0-7144-421b-a2b9-62c2d5bc7bcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/input</value>
      <webElementGuid>2cfb9781-9059-40f4-a313-ac8ee19c5dd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'netto']</value>
      <webElementGuid>f68a8c7d-81f7-4180-b110-031cd24e384c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
