<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Pelanggan</name>
   <tag></tag>
   <elementGuidId>462ae3d3-6acf-4ad4-8a77-e8e0c306eca0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DaftarKontak > div.collapse-content > ul.submenu-list > li > a.submenu-item > div.submenu-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[normalize-space()='Pelanggan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e83ce800-4f26-4ea4-837b-3f32f4e4fd4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>submenu-text</value>
      <webElementGuid>b2bc00e3-523b-4831-8427-d1b58c903729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pelanggan</value>
      <webElementGuid>aca32611-c687-46e0-9486-9d29ea52c203</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DaftarKontak&quot;)/div[@class=&quot;collapse-content&quot;]/ul[@class=&quot;submenu-list&quot;]/li[1]/a[@class=&quot;submenu-item&quot;]/div[@class=&quot;submenu-text&quot;]</value>
      <webElementGuid>9d277699-b6a5-41a4-baa2-27e67fa4cec4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DaftarKontak']/div[2]/ul/li/a/div[2]</value>
      <webElementGuid>c529c618-0b32-43df-b212-568d318117a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Kontak'])[1]/following::div[5]</value>
      <webElementGuid>4c7a7834-ad14-4924-a38c-b83a500d12ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mesin'])[1]/following::div[10]</value>
      <webElementGuid>41508ebe-26d1-45f7-8510-d27ca42844ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Salesman'])[1]/preceding::div[3]</value>
      <webElementGuid>bfe41a2b-8f6c-4ea7-b103-3a76a50a53d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Supplier'])[1]/preceding::div[6]</value>
      <webElementGuid>63081052-b4af-45a9-b230-476e072f33bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pelanggan']/parent::*</value>
      <webElementGuid>dcb120d9-c343-40e5-b911-91d05bb94773</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[10]/div/div[2]/ul/li/a/div[2]</value>
      <webElementGuid>56367967-dba7-44b0-937c-5d22669ef399</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Pelanggan' or . = 'Pelanggan')]</value>
      <webElementGuid>5ca2e2fd-a931-4412-9846-e47fb7463f87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
