<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Pelanggan</name>
   <tag></tag>
   <elementGuidId>462ae3d3-6acf-4ad4-8a77-e8e0c306eca0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DaftarKontak > div.collapse-content > ul.submenu-list > li > a.submenu-item > div.submenu-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='DaftarKontak']/div[2]/ul/li/a/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d7f3bc29-4af4-43d6-a52f-93bc65b8108e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>submenu-text</value>
      <webElementGuid>8084a910-2e2f-4dc3-9f0e-a58a9a17cc5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pelanggan</value>
      <webElementGuid>5c223b24-9697-45a3-8f89-57399b4b7043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DaftarKontak&quot;)/div[@class=&quot;collapse-content&quot;]/ul[@class=&quot;submenu-list&quot;]/li[1]/a[@class=&quot;submenu-item&quot;]/div[@class=&quot;submenu-text&quot;]</value>
      <webElementGuid>f893e5c9-d51e-46a4-b038-1191f106b86c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DaftarKontak']/div[2]/ul/li/a/div[2]</value>
      <webElementGuid>d3f879a9-0003-4bce-8d55-958ffb72f3a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Kontak'])[1]/following::div[5]</value>
      <webElementGuid>b20f8b9d-31f8-425b-8719-4c7dc799bf9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mesin'])[1]/following::div[10]</value>
      <webElementGuid>df62c0c2-bcf9-4292-864b-12edffd2d158</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Salesman'])[1]/preceding::div[3]</value>
      <webElementGuid>fdbd60a6-ffda-4521-95d3-2070ae20925b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Supplier'])[1]/preceding::div[6]</value>
      <webElementGuid>a5bb2abd-2c26-464b-a79f-6ff70aeb6f95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pelanggan']/parent::*</value>
      <webElementGuid>028bea40-fe2d-43f2-87c0-8f7e0b09698c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[10]/div/div[2]/ul/li/a/div[2]</value>
      <webElementGuid>1565a57f-f7a1-421d-a5f0-8a6a3933f890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Pelanggan' or . = 'Pelanggan')]</value>
      <webElementGuid>bd5c6e35-d694-4b81-8e31-402aa4165a95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
