<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pelanggan</name>
   <tag></tag>
   <elementGuidId>ca6a51df-a1ac-4ef6-ad54-6b45f606dbf7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.client-action</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@class='client-action']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>046d5ef0-dc8b-4099-ac71-a524d8a7b8f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>client-action</value>
      <webElementGuid>20b2c615-2221-4bb7-af76-17b3b22d0317</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Pelanggan
          </value>
      <webElementGuid>cc6da0cb-a7e4-4fb7-9530-ec99681b47ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;fontawesome-i2svg-active fontawesome-i2svg-complete&quot;]/body[1]/div[@class=&quot;app&quot;]/div[@class=&quot;tile is-ancestor&quot;]/div[@class=&quot;tile is-parent is-vertical main-content&quot;]/div[@class=&quot;router-content tile is-child&quot;]/div[@class=&quot;app-content&quot;]/div[@class=&quot;content expenses&quot;]/div[@class=&quot;section-card&quot;]/div[@class=&quot;operationals-menu font-style-normal responsive-menu is-flex-desktop is-justify-content-end&quot;]/a[@class=&quot;button button-addActions responsive-button&quot;]/span[@class=&quot;client-action&quot;]</value>
      <webElementGuid>dd5f7855-25a3-44f5-ab75-fc9f590a0f82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Atur Ulang'])[1]/following::span[1]</value>
      <webElementGuid>900c00c0-64b5-4f32-b4ef-1873ea353a85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cari'])[1]/following::span[2]</value>
      <webElementGuid>6fd20e96-b78d-41ea-a562-a466b987bf55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download Excel'])[1]/preceding::span[2]</value>
      <webElementGuid>372f957b-757c-401f-927e-f6d68bdb5ca2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama'])[1]/preceding::span[3]</value>
      <webElementGuid>c5680721-4309-45da-8804-a6ea7b0eae5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a/span</value>
      <webElementGuid>330c46a9-2076-4f8c-9fd7-9eeb0b78ba92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '&#xd;
            Pelanggan&#xd;
          ' or . = '&#xd;
            Pelanggan&#xd;
          ')]</value>
      <webElementGuid>aec5c390-78e7-423d-8833-8086f0c6d5bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
