<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Batalkan</name>
   <tag></tag>
   <elementGuidId>7354d4df-3824-411c-871a-7fb5861c1cb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[normalize-space()='Batalkan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>footer.modal-card-foot > button.button > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5a45e2ca-a9c3-4e5f-b721-3279d4e87c78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Batalkan</value>
      <webElementGuid>3641d5e8-e51d-425e-a7ec-0b427e8f0a99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;fontawesome-i2svg-active fontawesome-i2svg-complete is-clipped&quot;]/body[1]/div[@class=&quot;dialog modal is-active&quot;]/div[@class=&quot;modal-card animation-content&quot;]/footer[@class=&quot;modal-card-foot&quot;]/button[@class=&quot;button&quot;]/span[1]</value>
      <webElementGuid>c47c2acf-b351-4a46-9501-b73ef631d568</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='menghapus'])[1]/following::span[1]</value>
      <webElementGuid>91af5007-d39d-471a-9450-a308180bcc7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::span[2]</value>
      <webElementGuid>8787f86c-2548-4c0a-af37-6521d6483581</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hapus'])[1]/preceding::span[1]</value>
      <webElementGuid>daf54393-f792-4809-94d6-475703c376ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Batalkan']/parent::*</value>
      <webElementGuid>bf23cd8c-59ff-465f-9c33-6022cfa36899</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/button/span</value>
      <webElementGuid>b26f9ef7-361e-459a-8449-907d61989b14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Batalkan' or . = 'Batalkan')]</value>
      <webElementGuid>462f002b-c085-42a9-9cb0-f9a47e016bd3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
