<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Daftar Barang</name>
   <tag></tag>
   <elementGuidId>2ae7bf10-eec2-4cf7-a333-0d2dde5b2fed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Inventaris > div.collapse-content > ul.submenu-list > li > a.submenu-item > div.submenu-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Inventaris']/div[2]/ul/li/a/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2d1e71fc-b586-47b1-82eb-a81c26d35f41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>submenu-text</value>
      <webElementGuid>d1d28b71-0ee9-41a8-94e9-2abb4bbc0114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Daftar Barang</value>
      <webElementGuid>69043cad-b413-4427-bc2a-80c36e3e2360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Inventaris&quot;)/div[@class=&quot;collapse-content&quot;]/ul[@class=&quot;submenu-list&quot;]/li[1]/a[@class=&quot;submenu-item&quot;]/div[@class=&quot;submenu-text&quot;]</value>
      <webElementGuid>807030cc-8b8d-4bde-bed1-f871233b49b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Inventaris']/div[2]/ul/li/a/div[2]</value>
      <webElementGuid>f5b52887-974b-4972-8498-1f4a7ed9ec95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inventaris'])[1]/following::div[5]</value>
      <webElementGuid>8a85d843-33de-4945-88b7-95355bdfc079</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proses Produksi'])[1]/following::div[10]</value>
      <webElementGuid>15dc6b60-dbd6-4954-b838-418f04d2ee27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Penyesuaian Stok'])[1]/preceding::div[3]</value>
      <webElementGuid>10a911f1-0604-4e54-9517-9853730e5450</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Penjualan'])[1]/preceding::div[5]</value>
      <webElementGuid>862ad710-7e8d-4228-829d-48e6fa15a1af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Daftar Barang']/parent::*</value>
      <webElementGuid>d0e198a5-f2fb-42c6-8dc9-25f63863a0ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/div/div[2]/ul/li/a/div[2]</value>
      <webElementGuid>b5c22eba-401c-4d24-8fc3-473e13b9fd49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Daftar Barang' or . = 'Daftar Barang')]</value>
      <webElementGuid>446b9886-1aab-4a94-9c85-1ba5010675c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
