<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Netto_netto</name>
   <tag></tag>
   <elementGuidId>a8d4d5f9-2313-4145-a0d3-26b7aed58f71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;netto&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='netto']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>89d2989a-98a1-44b3-8c69-45cfd593062a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ce6b81db-82d4-4038-9e4e-5064712df2a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input input</value>
      <webElementGuid>ab6d0bdb-6453-4ce9-982a-6a3ae43134f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>netto</value>
      <webElementGuid>609c5fcf-ac83-48e1-83f0-0a2ffe98751e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;invoice-mobile&quot;)/div[@class=&quot;section-card modal-content-custom&quot;]/div[@class=&quot;section-content with-separator&quot;]/div[3]/div[@class=&quot;columns form-title&quot;]/div[@class=&quot;column&quot;]/div[@class=&quot;field&quot;]/input[@class=&quot;input input&quot;]</value>
      <webElementGuid>17fed2ce-ceaa-4493-8487-7f129b87c562</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='netto']</value>
      <webElementGuid>6a30a7d0-436d-4ae1-94ff-d1d3f65d4173</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='invoice-mobile']/div[2]/div[2]/div[3]/div/div[2]/div/input</value>
      <webElementGuid>561e0de4-1be3-44e9-8fcd-8698618f92eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>5132876c-2477-4d8b-bbdb-c501895093ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'netto']</value>
      <webElementGuid>eab2cb38-a32d-4262-b122-23745068450b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
