<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Salesman</name>
   <tag></tag>
   <elementGuidId>8f1856d5-3c20-42fe-8bfd-8d410c157c92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DaftarKontak > div.collapse-content > ul.submenu-list > li:nth-of-type(2) > a.submenu-item > div.submenu-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='DaftarKontak']/div[2]/ul/li[2]/a/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>af2e8628-067a-4c0f-966c-ee43a5623aa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>submenu-text</value>
      <webElementGuid>7390fee4-fc7c-464d-83f9-10ee4f11f84a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Salesman</value>
      <webElementGuid>33ee0830-8439-4299-a1c7-fb490d21754f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DaftarKontak&quot;)/div[@class=&quot;collapse-content&quot;]/ul[@class=&quot;submenu-list&quot;]/li[2]/a[@class=&quot;submenu-item&quot;]/div[@class=&quot;submenu-text&quot;]</value>
      <webElementGuid>cbd8293e-fd7d-4226-8003-fd81ee27423c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DaftarKontak']/div[2]/ul/li[2]/a/div[2]</value>
      <webElementGuid>1d93fa94-5c38-4cb4-9cef-9f8add988502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pelanggan'])[1]/following::div[3]</value>
      <webElementGuid>22b5a6e8-2496-4a2b-a080-b19df63020a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Kontak'])[1]/following::div[8]</value>
      <webElementGuid>1f824ba7-d214-44d2-ac1b-bb6edcba7291</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Supplier'])[1]/preceding::div[3]</value>
      <webElementGuid>f6db3dcd-9691-4c05-82cf-0975936dc450</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A'])[1]/preceding::div[5]</value>
      <webElementGuid>68f144b3-48d4-425d-b83d-59f2cdaf9127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Salesman']/parent::*</value>
      <webElementGuid>337e02d9-a035-47f6-bfbb-3900e40871af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[10]/div/div[2]/ul/li[2]/a/div[2]</value>
      <webElementGuid>3dd76fc1-8d9f-4178-8d26-65ba1c1df206</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Salesman' or . = 'Salesman')]</value>
      <webElementGuid>cabfee57-ee86-43c3-8c15-6c6022330082</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
