<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama_Name</name>
   <tag></tag>
   <elementGuidId>de03050e-efab-4974-b686-fedcbac9a755</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;Name&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='Name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>06948e88-69dd-4d36-b4d3-ba1c26f0f915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>441ed174-cca8-41a7-b9f3-dfc9be147214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>1e97cafc-dccb-48d9-964e-a726251ed88c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>90</value>
      <webElementGuid>393b1c1a-74d1-457b-bdc4-34b24bde2c11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>754bcc94-bf61-4a6b-9d08-e9e1d9e053ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>618357ff-1194-400f-94b2-7e33bc44f612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;invoice-mobile&quot;)/div[@class=&quot;section-card modal-content-custom&quot;]/div[@class=&quot;section-content with-separator&quot;]/div[@class=&quot;columns is-multiline has-top-space-field&quot;]/div[@class=&quot;column is-full is-paddingless-btm&quot;]/div[@class=&quot;field is-marginless&quot;]/div[@class=&quot;control is-clearfix&quot;]/input[@class=&quot;input&quot;]</value>
      <webElementGuid>8a8b6e25-fe53-47d7-bd42-f39d80312b08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='Name']</value>
      <webElementGuid>5a9190ce-b168-425a-8c14-ed34ff906008</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='invoice-mobile']/div[2]/div[2]/div/div/div/div/input</value>
      <webElementGuid>510c5396-6c14-4d22-bf6e-697745b4ae0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>70be03e3-e3fd-48b4-a2d3-8ad1ab6ad5b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'Name']</value>
      <webElementGuid>fdf321e8-a602-4915-a34d-5c6841b66793</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
