<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_konfirm_namabarang</name>
   <tag></tag>
   <elementGuidId>064f4fd1-c527-43ff-91cc-366b1017e254</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='invoice-mobile']/div[2]/div/div/div[2]/div/div/div/div/table/tbody/tr/td/div/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.b-tooltip.is-light.is-right.is-large.is-multiline > div.tooltip-trigger</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8bfa146b-1987-4573-bd73-dace8ffa12fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tooltip-trigger</value>
      <webElementGuid>266d2c89-4f5a-423a-a22d-0e6f0fc90740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gula Pasir (edit)</value>
      <webElementGuid>a17c2622-cb3e-4e03-8652-b223f38d1b4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;invoice-mobile&quot;)/div[@class=&quot;modal-card&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;section-card&quot;]/div[@class=&quot;section-table&quot;]/div[@class=&quot;columns is-multiline&quot;]/div[@class=&quot;column is-12&quot;]/div[@class=&quot;b-table&quot;]/div[@class=&quot;table-wrapper has-mobile-cards&quot;]/table[@class=&quot;table&quot;]/tbody[1]/tr[1]/td[1]/div[@class=&quot;overflow-wrap&quot;]/div[@class=&quot;b-tooltip is-light is-right is-large is-multiline&quot;]/div[@class=&quot;tooltip-trigger&quot;]</value>
      <webElementGuid>fcc94686-d919-4f2c-ba7d-6c2ed65aaa2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='invoice-mobile']/div[2]/div/div/div[2]/div/div/div/div/table/tbody/tr/td/div/div/div[2]</value>
      <webElementGuid>b2b4e420-e3d6-4337-8dfa-18e30738dac5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gula Pasir (edit)'])[2]/following::div[1]</value>
      <webElementGuid>20ba0e68-a5ef-4604-9b35-ef800b71ec45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sesudah Penyesuian:'])[1]/following::div[4]</value>
      <webElementGuid>ac3bc9a6-1e68-427c-94bc-7eaccf2e40ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Catatan:'])[1]/preceding::div[1]</value>
      <webElementGuid>99a4b26d-8944-4687-8c1c-598419392a98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simpan'])[2]/preceding::div[2]</value>
      <webElementGuid>084712e8-eeb5-450d-8da5-54fb6b0cd1e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div[2]/div/div/div[2]/div/div/div/div/table/tbody/tr/td/div/div/div[2]</value>
      <webElementGuid>d9d74fe8-84f7-4d47-8ab0-ef1d646c9542</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Gula Pasir (edit)' or . = 'Gula Pasir (edit)')]</value>
      <webElementGuid>a15b75c2-b7f8-4eec-a03a-45ef08c4b824</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
