<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_search_barang</name>
   <tag></tag>
   <elementGuidId>c5477ce0-6c03-420d-aa8e-8ab46744bee4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='search'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.is-hidden-mobile > div > div.field.has-addons.custom-search > div.control > input.input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7d542596-cfc6-4aee-babd-23b953453cb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cari Nama, Kode, Deskripsi Barang</value>
      <webElementGuid>f6a566bb-3a5a-4cb6-94f2-f2d8d19e5b4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>6edf683f-7cfc-4f2d-9870-66d1dd260bd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f4c7fd71-ac4d-444d-bc90-e4b759ffb02d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;invoice-mobile&quot;)/div[@class=&quot;is-hidden-mobile&quot;]/div[1]/div[@class=&quot;field has-addons custom-search&quot;]/div[@class=&quot;control&quot;]/input[@class=&quot;input&quot;]</value>
      <webElementGuid>f2c72975-f8d6-401e-b8ae-d9323a4e2735</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='search'])[2]</value>
      <webElementGuid>9d43ea49-264d-4512-9b80-c02d31c104c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='invoice-mobile']/div[2]/div/div/div/input</value>
      <webElementGuid>a5179138-23b9-48ad-9521-fb58911eea0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div[2]/div/div/div/input</value>
      <webElementGuid>e86309cc-0e3d-4119-a698-d2796b854c61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Cari Nama, Kode, Deskripsi Barang' and @type = 'search']</value>
      <webElementGuid>ec550ce0-e46a-49ac-b7bb-28f4ec4a7406</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
