<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Laporan</name>
   <tag></tag>
   <elementGuidId>275c6358-20d8-4420-a069-84acf863504c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Laporan']/div/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.menu-item > div.menu-item-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c49fe59d-e7d5-477b-b418-1ca28bb2bf1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-item-text</value>
      <webElementGuid>0cf1ee6a-d7b7-48ac-80ac-0ce38510f048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Laporan</value>
      <webElementGuid>cd8c0fba-fdf7-4abe-80e3-9efce88aefe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Laporan&quot;)/div[@class=&quot;collapse-trigger&quot;]/div[@class=&quot;menu-item&quot;]/div[@class=&quot;menu-item-text&quot;]</value>
      <webElementGuid>3f1350c6-0f54-4b97-a468-c472c8f6d012</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Laporan']/div/div/div[2]</value>
      <webElementGuid>3230aa72-5828-43bf-aa2c-63ea96eb7514</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Smart Search'])[1]/following::div[5]</value>
      <webElementGuid>f990383c-4993-4e4c-b906-0b088d28a6ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beranda'])[1]/following::div[7]</value>
      <webElementGuid>eb04110a-033b-4a71-90c9-a622ef116b1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kartu Stock'])[1]/preceding::div[4]</value>
      <webElementGuid>c61751c3-8800-44a0-b36c-474e7791821d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laporan Barang'])[1]/preceding::div[7]</value>
      <webElementGuid>2e664bc6-e11d-40e9-8b82-b0e99ee62659</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Laporan']/parent::*</value>
      <webElementGuid>c198c817-eccf-4d36-a470-283f423384da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[47]/div/div/div/div[2]</value>
      <webElementGuid>9cbf318e-dea4-4b1f-bb9c-ac2372ad11da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Laporan' or . = 'Laporan')]</value>
      <webElementGuid>0ae1dca6-c27b-4a35-a285-cb54bccae13d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
